services:

 # -------------------- BACKEND --------------------
  backend:
    container_name: promo_ml_backend
    image: promo-ml:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MODEL_PATH: /app/data/models_history/latest_model.pkl
      ENV: prod
      LOG_LEVEL: INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - promo_net

# -------------------- POSTGRES --------------------
  postgres:
    image: postgres:15
    container_name: promo_postgres
    restart: always
    environment:
      POSTGRES_DB: promo
      POSTGRES_USER: promo_user
      POSTGRES_PASSWORD: promo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - promo_net

# -------------------- REDIS --------------------
  redis:
    image: redis:latest
    container_name: promo_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - promo_net

# -------------------- NGINX --------------------
  nginx:
    image: nginx:latest
    container_name: promo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - promo_net

# -------------------- LOKI --------------------
  loki:
    image: grafana/loki:2.9.2
    container_name: promo_loki
    restart: always
    volumes:
      - ./docker/loki/loki-config.yml:/etc/loki/loki-config.yml
      - ./docker/loki/data:/var/loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - promo_net

# -------------------- PROMTAIL --------------------
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promo_promtail
    restart: always
    volumes:
      - ./logs:/logs
      - ./docker/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - promo_net

# -------------------- GRAFANA --------------------
  grafana:
    image: grafana/grafana:10.2.2
    container_name: promo_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - promo_net

networks:
  promo_net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  loki-data:
