# version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: promo_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - promo_net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promo_promtail
    volumes:
      - /var/log:/var/log
      - ../logs:/var/log/promo-ml    # ← считываем наши локальные логи
      - ./promtail/promtail-config.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - promo_net
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.3.0
    container_name: promo_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - promo_net

networks:
  promo_net:
    external: true

volumes:
  grafana_data:
  loki_data:
