version: "3.9"

services:

  backend:
    container_name: promo_ml_backend
    build:
      context: ..
      dockerfile: Dockerfile      # ← теперь путь КОРНЕВОЙ
    restart: always
    environment:
      - MODEL_PATH=/app/data/models_history/latest_model.pkl
      - ENV=prod
      - LOG_LEVEL=INFO
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - promo_net

  postgres:
    image: postgres:15
    container_name: promo_postgres
    restart: always
    environment:
      POSTGRES_DB: promo
      POSTGRES_USER: promo_user
      POSTGRES_PASSWORD: promo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - promo_net

  redis:
    image: redis:7
    container_name: promo_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - promo_net

  nginx:
    image: nginx:latest
    container_name: promo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - promo_net

networks:
  promo_net:
    driver: bridge

volumes:
  postgres_data:
