apiVersion: 1

datasources:
  - name: Loki
    uid: loki                # ← ОБЯЗАТЕЛЬНО
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    readOnly: true

    jsonData:
      maxLines: 3000
